export * from './subject.model'
export * from './student.model'
export * from './city.model'
export * from './professor.model'
export * from './title.model'
export * from './exam-period.model'
export * from './exam.model'
export * from './exam-registration.model'
